version: '3.8'

services:
  email-monitor:
    build: .
    container_name: email-monitor
    restart: unless-stopped
    volumes:
      - ./config.json:/app/config.json:ro
      - ./logs:/app/logs
    environment:
      - TZ=Europe/Paris
    # Optionnel: limitation des ressources
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    # Surveillance de santé
    healthcheck:
      test: ["CMD", "python", "-c", "import json; json.load(open('config.json'))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 